language: php

php:
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

branches:
  except:
    - gh-pages

before_script:
	- composer install
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run
