#!/bin/bash

# This script creates new test files with new random modifications 
# before every commit so that Migrate->gitDiff can be tested
# Copy this file to ".git/hooks/" to generate new files for testing

# Remove the files if they exist
filesArray=("test_includes/drop_fruit{$RANDOM}.sql" "test_includes/insert_fruit{$RANDOM}.sql" "test_includes/update_fruit{$RANDOM}.sql")

# Delete all the files
rm -f test_includes/*
for path in "${filesArray[@]}"
do
  touch $path
  echo "INSERT INTO fruit (name, color) VALUES ('plum', $RANDOM);" >> $path
done

# Add the new files to git and commit along with the commit that triggers this hook
git add -A